# Generated by Django 4.2 on 2023-10-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='verification_code',
            field=models.CharField(default='unavailable', editable=False, max_length=700, unique=True),
        ),
    ]
