# Generated by Django 4.2 on 2023-09-27 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_tenant_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 27, 23, 7, 19, 13611, tzinfo=datetime.timezone.utc)),
        ),
    ]
