# Generated by Django 4.2 on 2023-11-03 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='emial',
            new_name='email',
        ),
    ]
