# Generated by Django 4.2 on 2023-09-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tenant_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
