# Generated by Django 4.2 on 2023-10-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_booking_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='verification_code',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
