# Generated by Django 4.2 on 2023-10-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tenant_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='verification_code',
            field=models.CharField(default='unavailable', max_length=300, unique=True),
        ),
    ]
