# Generated by Django 4.2.7 on 2023-12-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_booking_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_updating_vcode',
            field=models.BooleanField(default=False),
        ),
    ]
