# Generated by Django 4.2.7 on 2024-01-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_booking_is_updating_vcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
