# Generated by Django 4.2.7 on 2024-01-30 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_tenant_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
