# Generated by Django 4.2.7 on 2024-02-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_tenant_end_date_alter_tenant_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='amount_left_to_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8, verbose_name='AMOUNT LEFT TO PAY'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='made_part_payment',
            field=models.BooleanField(default=False, verbose_name='Made Part Payment'),
        ),
    ]
