# Generated by Django 4.2.7 on 2024-02-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_tenant_amount_left_to_pay_tenant_made_part_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='amount_left_to_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='AMOUNT LEFT TO PAY'),
        ),
    ]
