# Generated by Django 4.2.7 on 2024-02-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_tenant_made_part_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='completed_payment',
            field=models.BooleanField(default=False, verbose_name='COMPLETED PAYMENT'),
        ),
    ]
