# Generated by Django 4.2.7 on 2024-02-10 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_customuser_campus_remove_customuser_college_and_more'),
        ('core', '0018_tenant_completed_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneralNewsLetter',
        ),
        migrations.DeleteModel(
            name='NewsletterEmails',
        ),
        migrations.DeleteModel(
            name='NewsLetterMessage',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.student'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.student'),
        ),
    ]
