# Generated by Django 4.2.7 on 2024-02-10 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_customuser_campus_remove_customuser_college_and_more'),
        ('core', '0019_delete_generalnewsletter_delete_newsletteremails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.student'),
        ),
    ]
