# Generated by Django 4.2.7 on 2024-02-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_booking_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
