# Generated by Django 4.2.7 on 2024-02-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_tenant_end_date_alter_tenant_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
