# Generated by Django 4.2.7 on 2024-02-17 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_otpcodedata_phone'),
        ('core', '0022_alter_tenant_end_date_alter_tenant_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.student'),
        ),
    ]
