# Generated by Django 4.2.7 on 2024-03-03 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='room_number',
        ),
    ]
