# Generated by Django 4.2.7 on 2023-12-16 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus_guest_house', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guesthouse',
            old_name='guest_hosue_name',
            new_name='guest_house_name',
        ),
    ]
