# Generated by Django 4.2.7 on 2023-12-17 23:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0014_campusprofile_alias_name'),
        ('campus_guest_house', '0003_guesthouse_house_code_guesthouse_house_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guest_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('phone', models.CharField(max_length=14)),
                ('phone_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Guest',
                'verbose_name_plural': 'Guests',
            },
        ),
        migrations.CreateModel(
            name='GuestHouseRooms',
            fields=[
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('room_image', models.ImageField(default='room_img_unavailable.jpg', upload_to='GuestHouseRoomImages')),
                ('room_type', models.CharField(max_length=50)),
                ('room_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campus_app.campusprofile')),
                ('guest_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_guest_house.guesthouse')),
            ],
            options={
                'verbose_name': 'GuestHouseRooms',
                'verbose_name_plural': 'GuestHouseRoomss',
            },
        ),
        migrations.CreateModel(
            name='GuestPaymentHistory',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reference', models.CharField(default='unavailable', editable=False, max_length=500, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=1, max_digits=7)),
                ('account_payed_to', models.CharField(max_length=300)),
                ('successful', models.BooleanField(default=False)),
                ('date_of_payment', models.DateTimeField(auto_now_add=True)),
                ('guest_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campus_guest_house.guest')),
                ('hostel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campus_guest_house.guesthouse')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campus_guest_house.guesthouserooms')),
            ],
        ),
        migrations.CreateModel(
            name='GuestBooking',
            fields=[
                ('room_number', models.CharField(max_length=20)),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('payed', models.BooleanField(default=False)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_app.campusprofile')),
                ('guest_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_guest_house.guesthouse')),
                ('guest_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_guest_house.guest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_guest_house.guesthouserooms')),
            ],
            options={
                'ordering': ('-start_time',),
            },
        ),
    ]
