# Generated by Django 4.2.7 on 2024-02-07 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus_app', '0025_alter_campusprofile_end_of_acadamic_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('mobile_money', models.CharField(max_length=10)),
                ('verifified', models.BooleanField(default=False)),
                ('campus_affiliation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='campus_app.campusprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HostelAgent',
                'verbose_name_plural': 'HostelAgents',
            },
        ),
    ]
