# Generated by Django 4.2.7 on 2024-02-07 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostelagent',
            old_name='verifified',
            new_name='verified',
        ),
    ]
