# Generated by Django 4.2.7 on 2024-02-07 21:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agents_app', '0002_rename_verifified_hostelagent_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostelagent',
            options={'verbose_name': 'Hostel Agent', 'verbose_name_plural': 'Hostel Agents'},
        ),
        migrations.RenameField(
            model_name='hostelagent',
            old_name='verified',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='hostelagent',
            name='agent_code',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hostelagent',
            name='agent_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='hostelagent',
            name='agent_profile_picture',
            field=models.ImageField(default='unknown_profile.jpg', upload_to='AgentsProfilePictures'),
        ),
        migrations.AddField(
            model_name='hostelagent',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
