# Generated by Django 4.2.7 on 2024-02-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_app', '0003_alter_hostelagent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelagent',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
