# Generated by Django 4.2.7 on 2024-03-02 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents_app', '0005_agentsales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelagent',
            name='campus_affiliation',
        ),
        migrations.RemoveField(
            model_name='hostelagent',
            name='user',
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_code', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('mobile_money', models.CharField(max_length=10)),
                ('agent_profile_picture', models.ImageField(default='unknown_profile.jpg', upload_to='AgentProfilePictures')),
                ('ghana_card', models.ImageField(default='unknown_profile.jpg', upload_to='AgentIDPictures')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('agent_code_generated', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
            },
        ),
        migrations.AlterField(
            model_name='agentsales',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents_app.agent'),
        ),
    ]
