# Generated by Django 4.2.7 on 2024-03-02 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents_app', '0006_remove_hostelagent_campus_affiliation_and_more'),
        ('hostel_app', '0064_alter_hostelprofile_agent_affiliate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HostelAgent',
        ),
    ]
