# Generated by Django 4.2.7 on 2024-03-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_app', '0008_remove_agent_agent_code_generated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_code',
            field=models.CharField(default=28687, editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
