# Generated by Django 4.2.7 on 2024-03-03 11:59

import agents_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_app', '0010_agent_date_join_agent_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_code',
            field=models.CharField(default=agents_app.models.genrate_agent_code, editable=False, max_length=7, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='mobile_money',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
