# Generated by Django 4.2.7 on 2024-03-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_app', '0011_alter_agent_agent_code_alter_agent_mobile_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentsales',
            name='amount_made',
        ),
        migrations.AddField(
            model_name='agentsales',
            name='number_of_sales',
            field=models.IntegerField(default=0),
        ),
    ]
