# Generated by Django 4.2.7 on 2024-03-03 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents_app', '0012_remove_agentsales_amount_made_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgentSales',
            new_name='AgentSale',
        ),
        migrations.AlterModelTable(
            name='agentsale',
            table='agent_sales',
        ),
    ]
