# Generated by Django 4.2 on 2023-10-07 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms_app', '0001_initial'),
        ('hostel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaystackSubAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bussiness_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=30)),
                ('subaccount_code', models.CharField(default='unavailable', max_length=50)),
                ('bank_code', models.CharField(default='unavailable', max_length=50)),
                ('settlement_bank', models.CharField(default='unavailable', max_length=80)),
                ('percentage_charge', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('account_verified', models.BooleanField(default=False)),
                ('hostel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hostel_app.hostelprofile')),
            ],
            options={
                'db_table': 'paystack_sub_accounts',
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=1, max_digits=7)),
                ('account_payed_to', models.CharField(max_length=300)),
                ('successfull', models.BooleanField(default=False)),
                ('date_of_payment', models.DateTimeField(auto_now_add=True)),
                ('hostel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel_app.hostelprofile')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms_app.roomprofile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
