# Generated by Django 4.2 on 2023-10-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystacksubaccount',
            name='subaccount_code',
            field=models.CharField(default='unavailable', max_length=50, unique=True),
        ),
    ]
