# Generated by Django 4.2 on 2023-09-27 15:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='reference',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='payment_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='account_payed_to',
            field=models.CharField(max_length=300),
        ),
    ]
