# Generated by Django 4.2 on 2023-09-29 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0016_rename_phone_hostelprofile_contact'),
        ('payments_app', '0003_alter_paymenthistory_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaystackSubAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bussiness_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=30)),
                ('bank_code', models.CharField(max_length=20)),
                ('percentage_charge', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hostel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hostel_app.hostelprofile')),
            ],
            options={
                'db_table': 'paystack_sub_accounts',
            },
        ),
    ]
