# Generated by Django 4.2 on 2023-09-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_app', '0004_paystacksubaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystacksubaccount',
            name='bank_code',
            field=models.CharField(default='unavailable', max_length=20),
        ),
        migrations.AlterField(
            model_name='paystacksubaccount',
            name='percentage_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
