# Generated by Django 4.2 on 2023-10-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_app', '0004_alter_paymenthistory_date_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='date_of_payment',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
