# Generated by Django 4.2 on 2023-10-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments_app', '0005_alter_paymenthistory_date_of_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='successfull',
            new_name='successful',
        ),
    ]
