# Generated by Django 4.2 on 2023-09-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_app', '0005_alter_paystacksubaccount_bank_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystacksubaccount',
            name='subaccount_code',
            field=models.CharField(default='unavailable', max_length=50),
        ),
    ]
