# Generated by Django 4.2 on 2023-09-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_app', '0006_paystacksubaccount_subaccount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystacksubaccount',
            name='account_verified',
            field=models.BooleanField(default=False),
        ),
    ]
