# Generated by Django 4.2 on 2023-10-19 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments_app', '0006_rename_successfull_paymenthistory_successful'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
