# Generated by Django 4.2 on 2023-10-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_app', '0007_alter_paymenthistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='access_code_used',
            field=models.CharField(default='unavailable', editable=False, max_length=500, unique=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='trxref',
            field=models.CharField(default='Not recieved', editable=False, max_length=500, unique=True),
        ),
    ]
