# Generated by Django 4.2 on 2023-09-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_app', '0007_paystacksubaccount_account_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paystacksubaccount',
            name='bank_code',
        ),
        migrations.AddField(
            model_name='paystacksubaccount',
            name='settlement_bank',
            field=models.CharField(default='unavailable', max_length=80),
        ),
    ]
