# Generated by Django 4.2 on 2023-10-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_app', '0008_paymenthistory_access_code_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='access_code_used',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='trxref',
        ),
        migrations.AddField(
            model_name='paystacksubaccount',
            name='primary_contact_name',
            field=models.CharField(default='unavailable', max_length=30),
        ),
        migrations.AlterField(
            model_name='paystacksubaccount',
            name='account_number',
            field=models.CharField(max_length=50),
        ),
    ]
