# Generated by Django 4.2.7 on 2023-12-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_app', '0009_remove_paymenthistory_access_code_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='paystack_reference',
            field=models.CharField(default='unavailable', max_length=500),
        ),
    ]
