# Generated by Django 4.2 on 2023-09-29 19:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments_app', '0010_remove_paystacksubaccount_account_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystacksubaccount',
            name='account_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paystacksubaccount',
            name='settlement_bank',
            field=models.CharField(default='unavailable', max_length=80),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='paystacksubaccount',
            name='bank_code',
            field=models.CharField(default='unavailable', max_length=50),
        ),
    ]
