# Generated by Django 4.2.7 on 2023-12-19 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments_app', '0010_paymenthistory_paystack_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='reference',
            new_name='reference_id',
        ),
    ]
