# Generated by Django 4.2 on 2023-09-29 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0019_alter_hostelprofile_options'),
        ('payments_app', '0012_remove_paymenthistory_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystacksubaccount',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_app.hostelprofile'),
        ),
    ]
