# Generated by Django 4.2.7 on 2024-01-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_app', '0012_alter_paymenthistory_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystacksubaccount',
            name='percentage_charge',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
    ]
