# Generated by Django 4.2.7 on 2024-01-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_app', '0015_alter_paystacksubaccount_percentage_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystacksubaccount',
            name='is_updating_subaccount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paystacksubaccount',
            name='update_message',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
