# Generated by Django 4.2.7 on 2024-01-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_app', '0016_paystacksubaccount_is_updating_subaccount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystacksubaccount',
            name='percentage_charge',
            field=models.DecimalField(decimal_places=3, default=3.381642512077295, max_digits=5, verbose_name='percentage charge %'),
        ),
    ]
