# Generated by Django 4.2.7 on 2024-01-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_app', '0017_alter_paystacksubaccount_percentage_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystacksubaccount',
            name='percentage_charge',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='percentage charge %'),
        ),
    ]
