# Generated by Django 4.2.7 on 2024-02-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_app', '0018_alter_paystacksubaccount_percentage_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='is_half_payment',
            field=models.BooleanField(default=False),
        ),
    ]
