# Generated by Django 4.2.7 on 2024-02-14 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_otpcodedata_phone'),
        ('payments_app', '0020_paymenthistory_completed_full_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='user',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.student'),
        ),
    ]
