# Generated by Django 4.2.7 on 2024-03-15 15:25

from django.db import migrations, models
import django.db.models.deletion
import payments_app.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0073_remove_hostelprofile_hostel_router_id'),
        ('accounts', '0019_rename_is_hostel_agent_customuser_is_bookmie_agent'),
        ('rooms_app', '0042_remove_roomprofile_rating'),
        ('payments_app', '0021_remove_paymenthistory_user_paymenthistory_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystacksubaccount',
            name='subaccount_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PhysicalPaymentHistory',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reference', models.CharField(default=payments_app.models.genrate_reference, editable=False, max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('account_payed_to', models.CharField(default='123-123-123-123-123456', max_length=20)),
                ('successful', models.BooleanField(default=False)),
                ('date_of_payment', models.DateTimeField(auto_now_add=True)),
                ('hostel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel_app.hostelprofile')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms_app.roomprofile')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
    ]
