# Generated by Django 4.2 on 2023-10-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_hostel_worker',
            field=models.BooleanField(default=False, verbose_name='Hostel Woker'),
        ),
    ]
