# Generated by Django 4.2 on 2023-10-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_hostel_manager',
            field=models.BooleanField(default=False),
        ),
    ]
