# Generated by Django 4.2 on 2023-10-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_hostel_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_hostel_manager',
            field=models.BooleanField(default=False, verbose_name='manager'),
        ),
    ]
