# Generated by Django 4.2.7 on 2023-12-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='unknown_profile.jpg', upload_to='ManagersProfile'),
        ),
    ]
