# Generated by Django 4.2.7 on 2023-12-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='unknown_profile.png', upload_to='ManagersProfile'),
        ),
    ]
