# Generated by Django 4.2.7 on 2024-02-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_hostel_agent',
            field=models.BooleanField(default=False, verbose_name='Hostel Agent'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_hostel_manager',
            field=models.BooleanField(default=False, verbose_name='Manager'),
        ),
    ]
