# Generated by Django 4.2.7 on 2024-02-10 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0025_alter_campusprofile_end_of_acadamic_year'),
        ('accounts', '0011_customuser_is_hostel_agent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='college',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='student_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('college', models.CharField(blank=True, max_length=70, null=True)),
                ('campus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campus_app.campusprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
