# Generated by Django 4.2.7 on 2024-02-10 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_otpcodedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpcodedata',
            name='phone',
        ),
    ]
