# Generated by Django 4.2.7 on 2024-02-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_otpcodedata_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(default='', max_length=7),
        ),
    ]
