# Generated by Django 4.2.7 on 2024-02-23 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_customuser_is_hostel_worker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='student_id_number',
        ),
    ]
