# Generated by Django 4.2.7 on 2024-03-03 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_customuser_is_guest_house_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_hostel_agent',
            new_name='is_bookmie_agent',
        ),
    ]
