# Generated by Django 4.2.7 on 2024-04-01 22:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_customuser_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
