# Generated by Django 4.2.7 on 2024-02-18 23:58

from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='guest id')),
                ('phone', models.CharField(max_length=15, verbose_name='phone number')),
                ('quest_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='anonymous code')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('code_life_time', models.TimeField(blank=True, null=True, verbose_name='code life time')),
            ],
        ),
        migrations.CreateModel(
            name='GuestHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=100, verbose_name='Name')),
                ('house_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('house_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('house_image', models.ImageField(default='unavailable.jpg', upload_to='GuestHouseImage')),
                ('phone', models.CharField(max_length=13, verbose_name='Guess House Number')),
                ('mobile_money', models.CharField(default='unavailable', max_length=14)),
                ('account_number', models.CharField(default='unavailable', help_text='Can also be a mobile money account', max_length=70)),
                ('bank_code', models.CharField(choices=[('280100', 'Access Bank'), ('080100', 'ADB Bank Limited'), ('030100', 'Absa Bank Ghana Ltd'), ('MTN', 'MTN'), ('VOD', 'Vodafone'), ('ATL', 'AirtelTigo'), ('070101', 'ARB Apex Bank'), ('210100', 'Bank of Africa Ghana'), ('010100', 'Bank of Ghana'), ('300335', 'Best Point Savings and Loans'), ('140100', 'CAL Bank Limited'), ('340100', 'Consolidated Bank Ghana Limited'), ('130100', 'Ecobank Ghana Limited'), ('200100', 'FBNBank Ghana Limited'), ('240100', 'Fidelity Bank Ghana Limited'), ('170100', 'First Atlantic Bank Limited'), ('330100', 'First National Bank Ghana Limited'), ('040100', 'GCB Bank Limited'), ('230100', 'Guaranty Trust Bank (Ghana) Limited'), ('050100', 'National Investment Bank Limited'), ('360100', 'OmniBSCI Bank'), ('180100', 'Prudential Bank Limited'), ('110100', 'Republic Bank (GH) Limited'), ('300361', 'Services Integrity Savings and Loans'), ('090100', 'Société Générale Ghana Limited'), ('190100', 'Stanbic Bank Ghana Limited'), ('020100', 'Standard Chartered Bank Ghana Limited'), ('060100', 'United Bank for Africa Ghana Limited'), ('100100', 'Universal Merchant Bank Ghana Limited'), ('120100', 'Zenith Bank Ghana')], default='unavailable', max_length=50)),
                ('manager_contact', models.CharField(blank=True, max_length=10, verbose_name="Manager's Contact")),
                ('location', models.CharField(max_length=10, verbose_name='Main location')),
                ('address', django_google_maps.fields.AddressField(blank=True, max_length=200, null=True)),
                ('geolocation', django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Motel/GuestHouse',
                'verbose_name_plural': 'Motels/GuestHouses',
            },
        ),
        migrations.CreateModel(
            name='GuestHouseRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GuestPaymentHistory',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reference', models.CharField(default='unavailable', editable=False, max_length=500, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=1, max_digits=7)),
                ('account_payed_to', models.CharField(max_length=300)),
                ('successful', models.BooleanField(default=False)),
                ('date_of_payment', models.DateTimeField(auto_now_add=True)),
                ('guest_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quick_rooms.anonymousguest')),
                ('hostel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quick_rooms.guesthouse')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quick_rooms.guesthouserooms')),
            ],
        ),
        migrations.CreateModel(
            name='GuestBooking',
            fields=[
                ('room_number', models.CharField(max_length=20)),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('payed', models.BooleanField(default=False)),
                ('guest_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quick_rooms.guesthouse')),
                ('guest_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quick_rooms.anonymousguest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quick_rooms.guesthouserooms')),
            ],
            options={
                'ordering': ('-start_time',),
            },
        ),
    ]
