# Generated by Django 4.2.7 on 2024-02-20 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0028_alter_campusprofile_campus_id'),
        ('quick_rooms', '0002_guesthouseroom_alter_guestbooking_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbooking',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='campus_app.campusprofile'),
        ),
        migrations.AddField(
            model_name='guesthouseroom',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campus_app.campusprofile', verbose_name='Campus where Room is located'),
        ),
    ]
