# Generated by Django 4.2.7 on 2024-02-20 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quick_rooms', '0003_guestbooking_campus_guesthouseroom_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='guesthouse',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
