# Generated by Django 4.2.7 on 2024-02-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_rooms', '0005_alter_guesthouseroom_room_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guesthouseroom',
            name='room_name',
            field=models.CharField(default='unavailable', max_length=50),
        ),
    ]
