# Generated by Django 4.2.7 on 2024-02-20 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quick_rooms', '0006_guesthouseroom_room_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guesthouse',
            old_name='house_name',
            new_name='name',
        ),
    ]
