# Generated by Django 4.2.7 on 2024-02-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quick_rooms', '0007_rename_house_name_guesthouse_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guesthouseroom',
            old_name='quest_house',
            new_name='guest_house',
        ),
    ]
