# Generated by Django 4.2.7 on 2024-02-20 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0028_alter_campusprofile_campus_id'),
        ('quick_rooms', '0008_rename_quest_house_guesthouseroom_guest_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestbooking',
            name='room_number',
        ),
        migrations.AddField(
            model_name='guesthouse',
            name='campus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='campus_app.campusprofile'),
            preserve_default=False,
        ),
    ]
