# Generated by Django 4.2.7 on 2024-02-20 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quick_rooms', '0012_guesthouseroom_previous_price_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestpaymenthistory',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='quick_rooms.guestbooking'),
        ),
    ]
