# Generated by Django 4.2.7 on 2024-03-01 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campus_app', '0028_alter_campusprofile_campus_id'),
        ('quick_rooms', '0014_anonymousguest_encryption_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestHouseManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('manager_code', models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('mobile_money', models.CharField(max_length=10)),
                ('manager_profile_picture', models.ImageField(default='unknown_profile.jpg', upload_to='AgentsProfilePictures')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('campus_affiliation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='campus_app.campusprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guest House Manager',
                'verbose_name_plural': 'Guest House Managers',
            },
        ),
    ]
