# Generated by Django 4.2.7 on 2024-03-01 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quick_rooms', '0015_guesthousemanager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guesthouse',
            options={'verbose_name': 'Motel, GuestHouse', 'verbose_name_plural': 'Motels, GuestHouses'},
        ),
        migrations.AlterModelOptions(
            name='guesthouseroom',
            options={'verbose_name': 'Guest house room', 'verbose_name_plural': 'Guest house rooms'},
        ),
    ]
