# Generated by Django 4.2.7 on 2024-03-01 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quick_rooms', '0016_alter_guesthouse_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paystackguesthousesubaccount',
            options={'verbose_name': 'Paystack Account', 'verbose_name_plural': 'Paystack Accounts'},
        ),
    ]
