"""PAYSTACK UPSTREAM PERCENTAGE FOR SUBACCOUNT"""

def calculate_upstream_percentage(SUPPLY_COST_PERCENTAGE: float):
    SUPPLY_SHARE = SUPPLY_COST_PERCENTAGE/(1+SUPPLY_COST_PERCENTAGE)
    PERCENTAGE = SUPPLY_SHARE * 100
    return PERCENTAGE 