# Generated by Django 4.2 on 2023-09-23 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelProfile',
            fields=[
                ('hostel_name', models.CharField(max_length=50)),
                ('hostel_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('hostel_code', models.CharField(max_length=50, null=True)),
                ('hostel_pic', models.ImageField(default='unavailable.jpg', upload_to='Hostel_Profiles')),
                ('type_of_hostel', models.CharField(choices=[('Homestel🏠', 'Homestel'), ('Normal Hostel🏢', 'Normal Hostel'), ('Apartment💰', 'Apartment')], max_length=15)),
                ('class_Of_Hostel', models.CharField(choices=[('VIP✨🏅', 'VIP'), ('First Class✨', 'First Class'), ('Second Class✅', 'Second Class'), ('Normal Class☑️', 'Normal Class')], max_length=20)),
                ('hostel_rating', models.IntegerField(default=0)),
                ('no_of_likes', models.IntegerField(default=0)),
                ('price_range', models.CharField(blank=True, default='unavailable', max_length=50)),
                ('hostel_motto', models.CharField(blank=True, max_length=2000)),
                ('number_of_rooms', models.IntegerField(default=5)),
                ('hostel_email', models.EmailField(blank=True, max_length=254)),
                ('hostel_bank_details', models.CharField(max_length=20)),
                ('hostel_mobile_money_details', models.CharField(max_length=14)),
                ('managers_contact', models.CharField(blank=True, max_length=10)),
                ('hostel_phone', models.CharField(max_length=10)),
                ('hostel_location_specification', models.CharField(blank=True, max_length=500)),
                ('other_phone', models.CharField(blank=True, max_length=10)),
                ('on_map_location', models.CharField(default='unavailable', max_length=10000)),
                ('hostel_main_site', models.URLField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('occupied', models.BooleanField(default=False)),
                ('campus_of_hostel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campus_app.campusprofile')),
                ('hostel_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
