# Generated by Django 4.2 on 2023-09-24 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hostelprofile',
            table='hostel_profiles',
        ),
    ]
