# Generated by Django 4.2 on 2023-10-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelprofile',
            name='account_number',
            field=models.CharField(default='unavailable', max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='hostelprofile',
            name='mobile_money',
            field=models.CharField(default='unavailable', max_length=14, unique=True),
        ),
    ]
