# Generated by Django 4.2 on 2023-09-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0002_alter_hostelprofile_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelprofile',
            name='type_of_hostel',
            field=models.CharField(choices=[('Hostel🏢', 'Hostel'), ('Homestel🏠', 'Homestel'), ('Apartment💰', 'Apartment')], max_length=15, verbose_name='Type'),
        ),
    ]
