# Generated by Django 4.2 on 2023-09-25 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0003_alter_hostelprofile_type_of_hostel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelprofile',
            name='no_of_likes',
        ),
    ]
