# Generated by Django 4.2 on 2023-09-25 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0004_remove_hostelprofile_no_of_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostelprofile',
            old_name='hostel_bank_details',
            new_name='bank_details',
        ),
        migrations.RenameField(
            model_name='hostelprofile',
            old_name='hostel_mobile_money_details',
            new_name='mobile_money',
        ),
        migrations.RenameField(
            model_name='hostelprofile',
            old_name='hostel_phone',
            new_name='phone',
        ),
    ]
