# Generated by Django 4.2 on 2023-10-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0004_alter_hostelprofile_account_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostelprofile',
            old_name='managers_contact',
            new_name='manager_contact',
        ),
    ]
