# Generated by Django 4.2 on 2023-10-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0005_rename_managers_contact_hostelprofile_manager_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelprofile',
            name='contact',
            field=models.CharField(max_length=10, verbose_name="Hostel's Contact"),
        ),
        migrations.AlterField(
            model_name='hostelprofile',
            name='manager_contact',
            field=models.CharField(blank=True, max_length=10, verbose_name="Manager's Contact"),
        ),
        migrations.AlterField(
            model_name='hostelprofile',
            name='rating',
            field=models.IntegerField(choices=[(4, '⭐⭐⭐⭐'), (3, '⭐⭐⭐'), (2, '⭐⭐'), (1, '⭐')], default=1, verbose_name='Stars'),
        ),
    ]
