# Generated by Django 4.2 on 2023-09-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0005_rename_hostel_bank_details_hostelprofile_bank_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostelprofile',
            old_name='campus_of_hostel',
            new_name='campus',
        ),
        migrations.RenameField(
            model_name='hostelprofile',
            old_name='hostel_pic',
            new_name='hostel_image',
        ),
        migrations.RemoveField(
            model_name='hostelprofile',
            name='class_Of_Hostel',
        ),
        migrations.AddField(
            model_name='hostelprofile',
            name='class_of_hostel',
            field=models.CharField(choices=[('VIP✨🏅', 'VIP'), ('First Class✨', 'First Class'), ('Second Class✅', 'Second Class'), ('Normal Class☑️', 'Normal Class')], default=1, max_length=20, verbose_name='class'),
            preserve_default=False,
        ),
    ]
