# Generated by Django 4.2 on 2023-10-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0006_alter_hostelprofile_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelprofile',
            name='bank_code',
            field=models.CharField(choices=[('280100', 'Access Bank'), ('080100', 'ADB Bank Limited'), ('030100', 'Absa Bank Ghana Ltd'), ('MTN', 'MTN'), ('VOD', 'Vodafone'), ('ATL', 'AirtelTigo'), ('070101', 'ARB Apex Bank'), ('210100', 'Bank of Africa Ghana'), ('010100', 'Bank of Ghana'), ('300335', 'Best Point Savings and Loans'), ('140100', 'CAL Bank Limited'), ('340100', 'Consolidated Bank Ghana Limited'), ('130100', 'Ecobank Ghana Limited'), ('200100', 'FBNBank Ghana Limited'), ('240100', 'Fidelity Bank Ghana Limited'), ('170100', 'First Atlantic Bank Limited'), ('330100', 'First National Bank Ghana Limited'), ('040100', 'GCB Bank Limited'), ('230100', 'Guaranty Trust Bank (Ghana) Limited'), ('050100', 'National Investment Bank Limited'), ('360100', 'OmniBSCI Bank'), ('180100', 'Prudential Bank Limited'), ('110100', 'Republic Bank (GH) Limited'), ('300361', 'Services Integrity Savings and Loans'), ('090100', 'Société Générale Ghana Limited'), ('190100', 'Stanbic Bank Ghana Limited'), ('020100', 'Standard Chartered Bank Ghana Limited'), ('060100', 'United Bank for Africa Ghana Limited'), ('100100', 'Universal Merchant Bank Ghana Limited'), ('120100', 'Zenith Bank Ghana')], default='unavailable', max_length=50),
        ),
    ]
