# Generated by Django 4.2 on 2023-09-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0006_rename_campus_of_hostel_hostelprofile_campus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelprofile',
            name='type_of_hostel',
            field=models.CharField(choices=[('Hostel🏢', 'Hostel'), ('Homestel🏠', 'Homestel'), ('Apartment💰', 'Apartment')], default='Hostel', max_length=15, verbose_name='Type'),
        ),
    ]
