# Generated by Django 4.2 on 2023-10-30 07:12

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0007_alter_hostelprofile_bank_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelprofile',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hostelprofile',
            name='address',
            field=django_google_maps.fields.AddressField(default=None, max_length=200, null=True),
        ),
    ]
