# Generated by Django 4.2 on 2023-09-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0007_alter_hostelprofile_type_of_hostel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelprofile',
            name='class_of_hostel',
            field=models.CharField(choices=[('VIP✨🏅', 'VIP'), ('First Class✨', 'First Class'), ('Second Class✅', 'Second Class'), ('Normal Class☑️', 'Normal Class')], default='First Class', max_length=20, verbose_name='class'),
        ),
    ]
