# Generated by Django 4.2 on 2023-10-30 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0009_alter_hostelprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hostelprofile',
            name='geolocation',
        ),
    ]
