# Generated by Django 4.2 on 2023-09-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0009_alter_hostelprofile_class_of_hostel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelprofile',
            name='class_of_hostel',
        ),
        migrations.AddField(
            model_name='hostelprofile',
            name='rating',
            field=models.CharField(choices=[('⭐⭐⭐⭐', '4-stars'), ('⭐⭐⭐', '3-stars'), ('⭐⭐', '2-stars'), ('⭐', '1-star')], default='1-star', max_length=20, verbose_name='Stars'),
        ),
    ]
