# Generated by Django 4.2 on 2023-09-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0010_remove_hostelprofile_class_of_hostel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelprofile',
            name='hostel_rating',
        ),
        migrations.AlterField(
            model_name='hostelprofile',
            name='rating',
            field=models.CharField(choices=[('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐', '⭐⭐'), ('⭐', '⭐')], default='⭐', max_length=10, verbose_name='Stars'),
        ),
    ]
