# Generated by Django 4.2 on 2023-11-05 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0010_remove_hostelprofile_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostelprofile',
            old_name='contact',
            new_name='hostel_contact',
        ),
    ]
