# Generated by Django 4.2.2 on 2023-11-20 13:28

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0011_rename_contact_hostelprofile_hostel_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelprofile',
            name='hostel_motto',
        ),
        migrations.AddField(
            model_name='hostelprofile',
            name='address',
            field=django_google_maps.fields.AddressField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hostelprofile',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True),
        ),
    ]
