# Generated by Django 4.2.2 on 2023-11-20 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0012_remove_hostelprofile_hostel_motto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelprofile',
            name='map_location',
        ),
    ]
