# Generated by Django 4.2 on 2023-09-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0013_alter_hostelprofile_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostelprofile',
            old_name='on_map_location',
            new_name='map_location',
        ),
        migrations.RemoveField(
            model_name='hostelprofile',
            name='hostel_location_specification',
        ),
        migrations.AddField(
            model_name='hostelprofile',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
