# Generated by Django 4.2.7 on 2023-12-03 14:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0015_alter_hostelprofile_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelprofile',
            name='hostel_id',
            field=models.UUIDField(default=uuid.UUID('8ba7798b-b0ae-4535-a0a8-2ece60b2b6de'), editable=False, unique=True),
        ),
    ]
