# Generated by Django 4.2 on 2023-09-26 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0015_alter_hostelprofile_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostelprofile',
            old_name='phone',
            new_name='contact',
        ),
    ]
