# Generated by Django 4.2 on 2023-09-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0016_rename_phone_hostelprofile_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelprofile',
            name='bank_details',
        ),
        migrations.AddField(
            model_name='hostelprofile',
            name='bank_account',
            field=models.CharField(default='unavailable', max_length=50),
        ),
        migrations.AddField(
            model_name='hostelprofile',
            name='bank_code',
            field=models.CharField(default='unavailable', max_length=50),
        ),
        migrations.AlterField(
            model_name='hostelprofile',
            name='mobile_money',
            field=models.CharField(default='unavailable', max_length=14),
        ),
    ]
