# Generated by Django 4.2.7 on 2023-12-03 19:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0016_alter_hostelprofile_hostel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelprofile',
            name='hostel_id',
            field=models.UUIDField(default=uuid.UUID('81877f8c-95a9-4c66-9438-fc67407369fb'), editable=False, unique=True),
        ),
    ]
