# Generated by Django 4.2.7 on 2023-12-04 18:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0017_alter_hostelprofile_hostel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelprofile',
            name='hostel_id',
            field=models.UUIDField(default=uuid.UUID('6ffb849d-1eae-4a5a-9719-0e3cf5971c67'), editable=False, unique=True),
        ),
    ]
