# Generated by Django 4.2 on 2023-09-29 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0018_rename_bank_account_hostelprofile_account_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostelprofile',
            options={'ordering': ('-hostel_name',)},
        ),
    ]
