# Generated by Django 4.2 on 2023-09-29 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel_app', '0019_alter_hostelprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelprofile',
            name='hostel_manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostels', to=settings.AUTH_USER_MODEL),
        ),
    ]
