# Generated by Django 4.2 on 2023-10-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0020_alter_hostelprofile_hostel_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelprofile',
            name='rating',
            field=models.IntegerField(choices=[(5, '⭐⭐⭐⭐'), (3, '⭐⭐⭐'), (2, '⭐⭐'), (1, '⭐')], default='⭐', verbose_name='Stars'),
        ),
    ]
