# Generated by Django 4.2.7 on 2023-12-05 22:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0020_alter_hostelprofile_hostel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelprofile',
            name='hostel_id',
            field=models.UUIDField(default=uuid.UUID('d2af0f1f-3802-4dde-bb00-e1b7d2b59719'), editable=False, unique=True),
        ),
    ]
