# Generated by Django 4.2 on 2023-10-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0021_alter_hostelprofile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelprofile',
            name='hostel_image',
            field=models.ImageField(default='unavailable.jpg', upload_to='HostelProfiles'),
        ),
        migrations.AlterField(
            model_name='hostelprofile',
            name='rating',
            field=models.IntegerField(choices=[(4, '⭐⭐⭐⭐'), (3, '⭐⭐⭐'), (2, '⭐⭐'), (1, '⭐')], default='⭐', verbose_name='Stars'),
        ),
    ]
