# Generated by Django 4.2.7 on 2023-12-05 22:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0021_alter_hostelprofile_hostel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelprofile',
            name='hostel_id',
            field=models.UUIDField(default=uuid.UUID('84be6895-2d70-43de-bad9-e9b6caecba0f'), editable=False, unique=True),
        ),
    ]
