# Generated by Django 4.2 on 2023-10-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0022_alter_hostelprofile_hostel_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelprofile',
            name='hostel_main_site',
        ),
        migrations.AddField(
            model_name='hostelprofile',
            name='main_website',
            field=models.URLField(blank=True, null=True, verbose_name='Hostel Website'),
        ),
    ]
