# Generated by Django 4.2.7 on 2023-12-05 23:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0023_hostelprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostelprofile',
            old_name='profile_picture',
            new_name='hostel_manager_profile_picture',
        ),
        migrations.AlterField(
            model_name='hostelprofile',
            name='hostel_id',
            field=models.UUIDField(default=uuid.UUID('b270cd36-9692-4daa-b3dd-b2284351b4c6'), editable=False, unique=True),
        ),
    ]
