# Generated by Django 4.2.7 on 2023-12-07 13:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0025_alter_hostelprofile_hostel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelprofile',
            name='hostel_id',
            field=models.UUIDField(default=uuid.UUID('9684f3ed-9ee5-4ed8-9bd2-f6821d403eb0'), editable=False, unique=True),
        ),
    ]
