# Generated by Django 4.2.2 on 2023-12-08 08:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0026_alter_hostelprofile_hostel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelprofile',
            name='hostel_id',
            field=models.UUIDField(default=uuid.UUID('6fddde6f-bcb8-4e7c-ad9c-8e798e73b318'), editable=False, unique=True),
        ),
    ]
