# Generated by Django 4.2.7 on 2023-12-08 12:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0027_alter_hostelprofile_hostel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelprofile',
            name='hostel_id',
            field=models.UUIDField(default=uuid.UUID('265c669c-44c9-45e5-a118-1566ebe43ebd'), editable=False, unique=True),
        ),
    ]
