# Generated by Django 4.2.7 on 2023-12-08 14:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0028_alter_hostelprofile_hostel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelprofile',
            name='hostel_id',
            field=models.UUIDField(default=uuid.UUID('2b3ce999-ef39-45e9-b623-c52c9c6d5e36'), editable=False, unique=True),
        ),
    ]
