# Generated by Django 4.2.7 on 2023-12-08 14:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0029_alter_hostelprofile_hostel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelprofile',
            name='hostel_id',
            field=models.UUIDField(default=uuid.UUID('142dace2-59f7-4487-9322-1687f3d7e0ed'), editable=False, unique=True),
        ),
    ]
