# Generated by Django 4.2.7 on 2023-12-08 15:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0030_alter_hostelprofile_hostel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelprofile',
            name='hostel_id',
            field=models.UUIDField(default=uuid.UUID('8cd9dbd6-deab-4141-917c-659dafa72c71'), editable=False, unique=True),
        ),
    ]
