# Generated by Django 4.2.7 on 2023-12-08 15:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0031_alter_hostelprofile_hostel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelprofile',
            name='hostel_id',
            field=models.UUIDField(default=uuid.UUID('095ad768-06d7-4234-878e-397d1872f309'), editable=False, unique=True),
        ),
    ]
