# Generated by Django 4.2.2 on 2023-12-08 16:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0032_alter_hostelprofile_hostel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelprofile',
            name='hostel_id',
            field=models.UUIDField(default=uuid.UUID('fcf492ea-0d27-4358-99d7-f26cdfc8c8e8'), editable=False, unique=True),
        ),
    ]
