# Generated by Django 4.2.2 on 2023-12-08 19:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0033_alter_hostelprofile_hostel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelprofile',
            name='hostel_id',
            field=models.UUIDField(default=uuid.UUID('83ffc022-4293-4053-86fc-0496836b1c1f'), editable=False, unique=True),
        ),
    ]
