# Generated by Django 4.2.2 on 2023-12-08 19:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0035_alter_hostelprofile_hostel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelprofile',
            name='hostel_id',
            field=models.UUIDField(default=uuid.UUID('610e499f-bd01-42d1-adce-b8dde50deaaf'), editable=False, unique=True),
        ),
    ]
