# Generated by Django 4.2.2 on 2023-12-08 19:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0036_alter_hostelprofile_hostel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelprofile',
            name='hostel_id',
            field=models.UUIDField(default=uuid.UUID('ca1a7083-0747-47dd-9607-ab6d70cb01a7'), editable=False, unique=True),
        ),
    ]
