# Generated by Django 4.2.2 on 2023-12-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0041_rename_other_phone_hostelprofile_other_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelprofile',
            name='facilities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
