# Generated by Django 4.2.2 on 2023-12-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0042_hostelprofile_facilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelprofile',
            name='facilities',
            field=models.TextField(default='unavailable'),
        ),
    ]
