# Generated by Django 4.2.7 on 2023-12-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0043_alter_hostelprofile_facilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelprofile',
            name='hostel_manager_profile_picture',
            field=models.ImageField(default='unknown_profile.jpg', upload_to='ManagersProfilePictures'),
        ),
    ]
