# Generated by Django 4.2.7 on 2024-01-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0044_alter_hostelprofile_hostel_manager_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelprofile',
            name='room_image2',
            field=models.ImageField(default='unavailable.jpg', upload_to='RoomImages', verbose_name='Image2 of one room'),
        ),
        migrations.AddField(
            model_name='hostelprofile',
            name='room_image3',
            field=models.ImageField(default='unavailable.jpg', upload_to='RoomImages', verbose_name='Image3 of one room'),
        ),
    ]
