# Generated by Django 4.2.7 on 2024-02-02 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0046_hostelprofile_hostel_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelprofile',
            name='main_website',
        ),
    ]
