# Generated by Django 4.2.7 on 2024-02-07 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents_app', '0001_initial'),
        ('hostel_app', '0047_remove_hostelprofile_main_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelprofile',
            name='agent_affiliate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents_app.hostelagent'),
        ),
    ]
