# Generated by Django 4.2.7 on 2024-02-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0049_hostelprofile_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelprofile',
            name='message',
            field=models.TextField(default='Type New Message'),
        ),
    ]
