# Generated by Django 4.2.7 on 2024-02-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0050_alter_hostelprofile_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelprofile',
            name='no_of_likes',
            field=models.IntegerField(default=1, verbose_name='Likes'),
        ),
    ]
