# Generated by Django 4.2.7 on 2024-02-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0052_hostelprofile_main_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelprofile',
            name='no_of_likes',
            field=models.IntegerField(default=22, verbose_name='Likes'),
        ),
    ]
