# Generated by Django 4.2.7 on 2024-03-01 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0056_alter_hostelprofile_no_of_likes_hostelmanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelprofile',
            name='no_of_likes',
            field=models.IntegerField(default=26, verbose_name='Likes'),
        ),
        migrations.CreateModel(
            name='SalesStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date recorded')),
                ('last_updated', models.DateField(auto_now=True, verbose_name='last updated')),
                ('year', models.PositiveIntegerField(default=2024)),
                ('amount_made', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hostel_app.hostelprofile')),
            ],
            options={
                'verbose_name': 'Sales Stat',
                'verbose_name_plural': 'Sale Stats',
            },
        ),
    ]
