# Generated by Django 4.2.7 on 2024-03-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0057_alter_hostelprofile_no_of_likes_salesstatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelprofile',
            name='no_of_likes',
            field=models.IntegerField(default=3, verbose_name='Likes'),
        ),
    ]
