# Generated by Django 4.2.7 on 2024-03-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0064_alter_hostelprofile_agent_affiliate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelprofile',
            name='no_of_likes',
            field=models.IntegerField(default=33, verbose_name='Likes'),
        ),
    ]
