# Generated by Django 4.2.7 on 2024-03-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0068_alter_hostelprofile_no_of_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelprofile',
            name='no_of_likes',
            field=models.IntegerField(default=7, verbose_name='Likes'),
        ),
    ]
