# Generated by Django 4.2.7 on 2024-03-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0069_alter_hostelprofile_no_of_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelprofile',
            name='hostel_manager_profile_picture',
            field=models.ImageField(default='unavailable.jpg', upload_to='Management Images', verbose_name='Manager Profile'),
        ),
    ]
