# Generated by Django 4.2.7 on 2024-03-03 12:57

from django.db import migrations, models
import hostel_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0070_hostelprofile_hostel_manager_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelprofile',
            name='hostel_id',
        ),
        migrations.AlterField(
            model_name='hostelprofile',
            name='hostel_code',
            field=models.CharField(default=hostel_app.models.genrate_hostel_code, max_length=7, unique=True),
        ),
    ]
