# Generated by Django 4.2.7 on 2024-01-06 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesstatistics',
            options={'verbose_name': 'Sales Stat', 'verbose_name_plural': 'Sale Stats'},
        ),
    ]
