# Generated by Django 4.2.7 on 2024-01-08 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0045_hostelprofile_room_image2_hostelprofile_room_image3'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management_app', '0002_alter_salesstatistics_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('hostel', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostels', to='hostel_app.hostelprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
