# Generated by Django 4.2.7 on 2024-01-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0004_alter_worker_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='profile_picture',
            field=models.ImageField(default='unavailable.jpg', upload_to='WorkerImages', verbose_name='Portar Profile'),
        ),
    ]
