# Generated by Django 4.2.7 on 2024-01-26 19:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0005_worker_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='id',
        ),
        migrations.AddField(
            model_name='worker',
            name='worker_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='worker_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
