# Generated by Django 4.2.7 on 2024-02-20 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel_app', '0052_hostelprofile_main_website'),
        ('management_app', '0006_remove_worker_id_worker_worker_code_worker_worker_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('management_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('management_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('profile_picture', models.ImageField(default='unavailable.jpg', upload_to='WorkerImages', verbose_name='Portar Profile')),
                ('is_manager', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('hostel', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostels', to='hostel_app.hostelprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
