# Generated by Django 4.2.7 on 2024-03-01 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0055_remove_hostelprofile_hostel_manager_profile_picture_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management_app', '0007_management_delete_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelManagement',
            fields=[
                ('management_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('management_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('profile_picture', models.ImageField(default='unavailable.jpg', upload_to='Management Images', verbose_name='Management Profile')),
                ('is_manager', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('hostel', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostels', to='hostel_app.hostelprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Management',
        ),
    ]
