# Generated by Django 4.2.7 on 2024-03-01 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0008_hostelmanagement_delete_management'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HostelManagement',
        ),
    ]
