# Generated by Django 4.2.7 on 2024-03-01 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0009_delete_hostelmanagement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesStatistics',
        ),
    ]
