# Generated by Django 4.2 on 2023-09-23 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus_app', '0001_initial'),
        ('hostel_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomProfile',
            fields=[
                ('room_no', models.CharField(default=0, max_length=20)),
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('room_capacity', models.PositiveIntegerField(default=0)),
                ('room_img', models.ImageField(default='unavailable.jpg', upload_to='RoomImages')),
                ('room_price', models.DecimalField(decimal_places=1, max_digits=7)),
                ('room_category', models.CharField(choices=[('VIP✨🏅', 'VIP'), ('First Class✨', 'First Class'), ('Second Class✅', 'Second Class'), ('Normal Class☑️', 'Normal Class')], max_length=15)),
                ('occupied', models.BooleanField(default=False)),
                ('campus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campus_app.campusprofile', verbose_name='Campus where Room is located')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostel_app.hostelprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RoomForSale',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('seller_ID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('new_price', models.IntegerField()),
                ('valid', models.BooleanField(default=False)),
                ('info', models.TextField(blank=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_app.hostelprofile')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms_app.roomprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
