# Generated by Django 4.2 on 2023-10-07 15:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus_app', '0001_initial'),
        ('hostel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomProfile',
            fields=[
                ('room_no', models.CharField(default=0, max_length=20)),
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('room_capacity', models.PositiveIntegerField(default=4)),
                ('room_img', models.ImageField(default='unavailable.jpg', upload_to='RoomImages')),
                ('room_price', models.DecimalField(decimal_places=1, max_digits=7)),
                ('rating', models.IntegerField(choices=[(4, '⭐⭐⭐⭐'), (3, '⭐⭐⭐'), (2, '⭐⭐'), (1, '⭐')], default='⭐')),
                ('booking_occupied', models.BooleanField(default=False)),
                ('occupied', models.BooleanField(default=False)),
                ('campus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campus_app.campusprofile', verbose_name='Campus where Room is located')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostel_app.hostelprofile')),
            ],
            options={
                'db_table': 'room_profiles',
            },
        ),
    ]
