# Generated by Django 4.2 on 2023-09-24 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roomprofile',
            table='RoomProfile',
        ),
    ]
