# Generated by Django 4.2 on 2023-09-24 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0002_alter_roomprofile_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roomprofile',
            table='room_profile',
        ),
    ]
