# Generated by Django 4.2 on 2023-10-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0002_roomprofile_air_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomprofile',
            name='shared_bathroom',
        ),
    ]
