# Generated by Django 4.2 on 2023-09-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0004_alter_roomprofile_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomprofile',
            name='room_category',
        ),
        migrations.AddField(
            model_name='roomprofile',
            name='rating',
            field=models.CharField(choices=[('⭐⭐⭐⭐', '4-stars'), ('⭐⭐⭐', '3-stars'), ('⭐⭐', '2-stars'), ('⭐', '1-star')], default='1-star', max_length=15),
        ),
    ]
