# Generated by Django 4.2 on 2023-10-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0004_alter_roomprofile_floor_no_alter_roomprofile_room_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomprofile',
            name='contains_toilet',
            field=models.BooleanField(default=False),
        ),
    ]
