# Generated by Django 4.2 on 2023-09-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0005_remove_roomprofile_room_category_roomprofile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomprofile',
            name='rating',
            field=models.CharField(choices=[('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐', '⭐⭐'), ('⭐', '⭐')], default='1-star', max_length=15),
        ),
    ]
