# Generated by Django 4.2 on 2023-10-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0006_alter_roomprofile_floor_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomprofile',
            name='capacity_left',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
