# Generated by Django 4.2 on 2023-09-26 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0007_alter_roomprofile_rating_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomForSale',
        ),
    ]
