# Generated by Django 4.2 on 2023-10-28 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0007_roomprofile_capacity_left'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomprofile',
            old_name='contains_bathroom',
            new_name='inbuilt_bathroom',
        ),
        migrations.RenameField(
            model_name='roomprofile',
            old_name='contains_kitchen',
            new_name='inbuilt_kitchen',
        ),
        migrations.RenameField(
            model_name='roomprofile',
            old_name='contains_toilet',
            new_name='inbulit_balconi',
        ),
        migrations.RemoveField(
            model_name='roomprofile',
            name='shared_kitchen',
        ),
    ]
