# Generated by Django 4.2 on 2023-10-28 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0008_rename_contains_bathroom_roomprofile_inbuilt_bathroom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomprofile',
            old_name='inbulit_balconi',
            new_name='inbuilt_balconi',
        ),
    ]
