# Generated by Django 4.2 on 2023-10-28 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0009_rename_inbulit_balconi_roomprofile_inbuilt_balconi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomprofile',
            old_name='capacity_left',
            new_name='bed_space_left',
        ),
    ]
