# Generated by Django 4.2 on 2023-10-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0010_alter_roomprofile_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomprofile',
            name='booking_occupied',
            field=models.BooleanField(default=False),
        ),
    ]
