# Generated by Django 4.2 on 2023-10-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0011_alter_roomprofile_bed_space_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomprofile',
            name='bed_space_left',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
