# Generated by Django 4.2.2 on 2023-11-18 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0012_alter_roomprofile_bed_space_left'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomprofile',
            old_name='inbuilt_balconi',
            new_name='inbuilt_balcony',
        ),
    ]
