# Generated by Django 4.2.2 on 2023-12-02 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0013_rename_inbuilt_balconi_roomprofile_inbuilt_balcony'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomprofile',
            name='room_img',
        ),
    ]
