# Generated by Django 4.2.7 on 2023-12-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0014_remove_roomprofile_room_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomprofile',
            name='gender',
            field=models.CharField(choices=[('fem', 'female'), ('male', 'male')], default='male', max_length=20, verbose_name='Gender of room'),
        ),
    ]
