# Generated by Django 4.2.2 on 2023-12-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0021_alter_roomprofile_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomprofile',
            name='room_price',
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
    ]
