# Generated by Django 4.2.2 on 2023-12-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0022_alter_roomprofile_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomprofile',
            name='price_check',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True),
        ),
    ]
