# Generated by Django 4.2.2 on 2023-12-08 19:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0025_rename_price_check_roomprofile_previous_price_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomprofile',
            name='room_id',
            field=models.UUIDField(default=uuid.UUID('433aa055-4f5a-477c-aeef-b6ccdabeb489'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
