# Generated by Django 4.2.2 on 2023-12-08 19:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0026_alter_roomprofile_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomprofile',
            name='room_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
