# Generated by Django 4.2.2 on 2023-12-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0028_remove_roomprofile_previous_price_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomprofile',
            name='previous_price_check',
            field=models.DecimalField(blank=True, decimal_places=1, editable=False, max_digits=7, null=True),
        ),
    ]
