# Generated by Django 4.2.2 on 2023-12-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0029_roomprofile_previous_price_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomprofile',
            name='selling_price',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='roomprofile',
            name='room_price',
            field=models.DecimalField(decimal_places=1, max_digits=8),
        ),
    ]
