# Generated by Django 4.2.7 on 2023-12-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0033_roomprofile_booking_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomprofile',
            name='bed_space_left',
            field=models.IntegerField(default=0),
        ),
    ]
