# Generated by Django 4.2.7 on 2024-01-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0034_alter_roomprofile_bed_space_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomprofile',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male'), ('open', 'open')], default='male', max_length=20, verbose_name='Gender of room'),
        ),
    ]
