# Generated by Django 4.2.7 on 2024-02-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0036_alter_roomprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomprofile',
            name='accept_half_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomprofile',
            name='half_pricing',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8),
        ),
    ]
