# Generated by Django 4.2.7 on 2024-02-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0038_roomprofile_no_of_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomprofile',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
