# Generated by Django 4.2.7 on 2024-02-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0039_roomprofile_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomprofile',
            name='rating',
            field=models.IntegerField(choices=[(4, '⭐⭐⭐⭐'), (3, '⭐⭐⭐'), (2, '⭐⭐'), (1, '⭐')], default=1),
        ),
    ]
