# Generated by Django 4.2.7 on 2024-02-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0040_alter_roomprofile_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomprofile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
