# Generated by Django 4.2 on 2023-10-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0004_customercare_issue_resolved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReccomendationFeedBacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='Clients')),
                ('reccomendation', models.TextField()),
            ],
            options={
                'verbose_name': 'ReccomendationFeedBacks',
                'verbose_name_plural': 'ReccomendationFeedBacks',
            },
        ),
    ]
