# Generated by Django 4.2 on 2023-10-29 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0005_reccomendationfeedbacks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReccomendationFeedBacks',
            new_name='RecomendationFeedBacks',
        ),
        migrations.AlterModelOptions(
            name='recomendationfeedbacks',
            options={'verbose_name': 'RecomendationFeedBacks', 'verbose_name_plural': 'RecomendationFeedBacks'},
        ),
    ]
