# Generated by Django 4.2.7 on 2024-02-08 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0037_roomprofile_accept_half_payment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews_app', '0006_rename_reccomendationfeedbacks_recomendationfeedbacks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RoomLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms_app.roomprofile')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
