# Generated by Django 4.2.7 on 2024-02-08 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0050_alter_hostelprofile_message'),
        ('rooms_app', '0037_roomprofile_accept_half_payment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews_app', '0007_hostellikes_roomlikes'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_app.hostelprofile')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='RoomLikes',
            new_name='RoomLike',
        ),
        migrations.DeleteModel(
            name='HostelLikes',
        ),
    ]
