# Generated by Django 4.2.7 on 2024-02-28 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews_app', '0009_generalnewsletter_newsletteremails_newslettermessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostellike',
            name='user',
        ),
        migrations.DeleteModel(
            name='RoomLike',
        ),
        migrations.AddField(
            model_name='hostellike',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
