# Generated by Django 4.2.7 on 2024-03-26 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0010_remove_hostellike_user_delete_roomlike_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterEmails',
        ),
        migrations.DeleteModel(
            name='NewsLetterMessage',
        ),
    ]
