# Generated by Django 4.2.7 on 2024-03-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0012_faq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='answser',
            new_name='answer',
        ),
    ]
