# Generated by Django 4.2 on 2023-10-07 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_name', models.CharField(max_length=100)),
                ('campus_code', models.CharField(max_length=20)),
                ('flag', models.ImageField(default='defaultFlag.jpg', upload_to='CampusFlag')),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CollegesProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=100)),
                ('college_id', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=90)),
                ('campus_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_app.campusprofile')),
            ],
        ),
    ]
