# Generated by Django 4.2 on 2023-10-23 14:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusprofile',
            name='campus_uuid',
            field=models.UUIDField(default=uuid.UUID('35c62cfb-98be-49b3-9124-339054f22590')),
        ),
    ]
