# Generated by Django 4.2 on 2023-10-23 14:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0002_campusprofile_campus_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusprofile',
            name='campus_uuid',
            field=models.UUIDField(default=uuid.UUID('a1fb4423-b6cf-4439-8c01-2ae56cd57080'), editable=False),
        ),
    ]
