# Generated by Django 4.2 on 2023-10-23 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0005_alter_campusprofile_campus_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campusprofile',
            name='campus_uuid',
        ),
    ]
