# Generated by Django 4.2 on 2023-10-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0006_remove_campusprofile_campus_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusprofile',
            name='campus_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
