# Generated by Django 4.2.2 on 2023-11-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0007_alter_campusprofile_campus_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusprofile',
            name='available_on_campus',
            field=models.BooleanField(default=False),
        ),
    ]
