# Generated by Django 4.2.2 on 2023-11-29 09:48

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0008_campusprofile_available_on_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusprofile',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='campusprofile',
            name='address',
            field=django_google_maps.fields.AddressField(blank=True, max_length=200, null=True),
        ),
    ]
