# Generated by Django 4.2.2 on 2023-11-29 10:00

from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0012_alter_campusprofile_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=100)),
                ('college_id', models.CharField(max_length=100, unique=True)),
                ('address', django_google_maps.fields.AddressField(blank=True, max_length=200, null=True)),
                ('geolocation', django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True)),
                ('campus_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_app.campusprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='CollegesProfile',
        ),
    ]
