# Generated by Django 4.2.7 on 2024-01-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0014_campusprofile_alias_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusprofile',
            name='end_of_acadamic_year',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='campusprofile',
            name='available_on_campus',
            field=models.BooleanField(default=False, verbose_name='Bookmie.com Working on Campus'),
        ),
    ]
