# Generated by Django 4.2.7 on 2024-01-23 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0015_campusprofile_end_of_acadamic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusprofile',
            name='end_of_acadamic_year',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
