# Generated by Django 4.2.7 on 2024-01-26 15:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0017_alter_campusprofile_end_of_acadamic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusprofile',
            name='campus_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
