# Generated by Django 4.2.7 on 2024-01-26 15:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0018_campusprofile_campus_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusprofile',
            name='campus_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
