# Generated by Django 4.2.7 on 2024-02-10 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0025_alter_campusprofile_end_of_acadamic_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campusprofile',
            name='campus_id',
        ),
    ]
