# Generated by Django 4.2.7 on 2024-02-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0026_remove_campusprofile_campus_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusprofile',
            name='campus_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
