# Generated by Django 4.2.7 on 2024-02-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0027_campusprofile_campus_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusprofile',
            name='campus_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
