# Generated by Django 4.2.7 on 2024-03-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0028_alter_campusprofile_campus_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collegeprofile',
            old_name='campus_name',
            new_name='campus',
        ),
        migrations.RemoveField(
            model_name='campusprofile',
            name='campus_id',
        ),
        migrations.RemoveField(
            model_name='collegeprofile',
            name='college_id',
        ),
        migrations.AddField(
            model_name='campusprofile',
            name='campus_param_id',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='collegeprofile',
            name='college_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='campusprofile',
            name='alias_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='campusprofile',
            name='campus_code',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='campusprofile',
            name='campus_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='collegeprofile',
            name='college_name',
            field=models.CharField(max_length=20),
        ),
    ]
